// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.AttorneysController.GetAttorneyDetail(System.Int32)~System.Threading.Tasks.Task{AdminApp.Data.Models.Attorney}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.AttorneysController.GetAttorneyDetail(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{AdminApp.Data.Models.Attorney}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.AttorneysController.Save(AdminApp.Data.Models.Attorney)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.AttorneysController.Save(AdminApp.Data.Models.Attorney)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Int32}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.AttorneysController.Get(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{AdminApp.Data.Models.Attorney}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.SettingsController.GetAll~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{AdminApp.Data.Models.Setting}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:App.Controllers.UsersController.Login(App.ViewModels.LoginModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:AdminApp.API.Controllers.AuthService.Authenticate(System.String,System.String)~System.Threading.Tasks.Task{AdminApp.API.Models.User}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:AdminApp.API.Services.AuthService.Authenticate(System.String,System.String)~System.Threading.Tasks.Task{AdminApp.API.Models.User}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:AdminApp.API.Controllers.SettingsController.GetEnabled(System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{AdminApp.API.Models.SettingDTO}}")]
