// <auto-generated />
namespace AdminApp.Data.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreatingTemplateDomainObjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatingTemplateDomainObjects));
        
        string IMigrationMetadata.Id
        {
            get { return "202101271152519_CreatingTemplateDomainObjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
